- name: git (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure vscode extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - bierner.github-markdown-preview
        - eamodio.gitlens
        - github.vscode-pull-request-github
        - fabiospampinato.vscode-github-notifications-bell
