- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    # macOS

    - name: Ensure Homebrew and all packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
    
    - name: Tap microsfot Cask
      homebrew_tap:
        name: microsoft/mssql-release
        
    - name: Ensure core packages
      homebrew:
        name: "{{ item }}"
      loop:
        - bat
        - htop
        - jq
        - msodbcsql@13.1.9.2
        - mssql-tools@14.0.6.0

    - name: Ensure terminal
      homebrew_cask:
        name: iterm2
