- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    # macOS

    - name: Ensure Homebrew and all packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: Ensure core packages
      homebrew:
        name: "{{ item }}"
      loop:
        - bat
        - htop
        - jq

    - name: Ensure terminal
      homebrew_cask:
        name: iterm2
