- name: fonts
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Tap Font Cask
      homebrew_tap:
        name: homebrew/cask-fonts

    - name: Ensure custom fonts
      homebrew_cask:
        name: "{{ item }}"
      loop:
        - font-saucecodepro-nerd-font
        - font-fira-code-nerd-font
        - font-hasklug-nerd-font
        - font-iosevka-nerd-font
