- name: VS Code (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code Extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - streetsidesoftware.code-spell-checker           # Code Spell Checker
        - editorconfig.editorconfig                       # EditorConfig for VS Code
        - thenikso.github-plus-theme                      # GitHub Plus Theme
        - ms-vsliveshare.vsliveshare-pack                 # Live Share Extension Pack
        - pkief.material-icon-theme                       # Material Icon Theme
        - eamodio.toggle-excluded-files                   # Toggle Excluded Files
        - pflannery.vscode-versionlens                    # Version Lens
        - visualstudioexptteam.vscodeintellicode          # Visual Studio IntelliCode
        - ms-vscode-remote.vscode-remote-extensionpack    # Remote Development
        - auiworks.amvim                                  # vim
        - coenraads.bracket-pair-colorizer-2
        - vmsynkov.colonize
        - ryanluker.vscode-coverage-gutters
        - aeschli.vscode-css-formatter
        - mikestead.dotenv
        - grapecity.gc-excelviewer
        - sleistner.vscode-fileutils
        - mkxml.vscode-filesize
        - ee92.folderize
        - davidanson.vscode-markdownlint
        - ibm.output-colorizer
        - bradlc.vscode-tailwindcss
        - ryu1kn.partial-diff
        - taoklerks.poor-mans-t-sql-formatter-vscode
        - chrmarti.regex
        - shan.code-settings-sync
        - richie5um2.vscode-sort-json
        - mauve.terraform
        - ms-vscode.wordcount
        - dotjoshjohnson.xml
        - slevesque.vscode-zipexplorer
        - wart.ariake-dark
        - vscode-icons-team.vscode-icons

    - name: Ensure ~/.config folder exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Link '~/Library/Application Support/Code' to '~/.config/Code' (macOS)
      file:
        path: ~/.config/Code
        src: ~/Library/Application Support/Code
        state: link

    - name: Override default VS Code preferences
      copy:
        src: settings.json
        dest: ~/.config/Code/User/settings.json

    - name: Override default VS Code key bindings
      copy:
        src: keybindings.json
        dest: ~/.config/Code/User/keybindings.json
