- name: oh my zsh
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Check for zsh installation
      stat:
        path: ~/.zshrc
      register: zsh

    - name: Ensure oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      when: zsh.stat.exists != true

    - name: Ensure antigen
      homebrew:
        name: antigen

    - name: Ensure antigen configuration
      copy:
        dest: ~/.antigenrc
        content: |
          antigen use oh-my-zsh

          antigen bundle z
          antigen bundle brew
          antigen bundle colorize
          antigen bundle dotnet
          antigen bundle zsh_reload
          antigen bundle zsh-users/zsh-syntax-highlighting
          antigen bundle zsh-users/zsh-autosuggestions

          # antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train
          THEME=caiogondim/bullet-train-oh-my-zsh-theme
          antigen list | grep $THEME; if [ $? -ne 0 ]; then antigen theme $THEME; fi

          if [[ "$OSTYPE" == "darwin"* ]]; then
              antigen bundle osx
          fi

          antigen apply

    - name: Ensure zshrc
      copy:
        dest: ~/.zshrc
        content: |
          source /usr/local/share/antigen/antigen.zsh
          antigen init ~/.antigenrc
