- name: Oh my zsh (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure enhanced terminal prompt
      blockinfile:
        dest: ~/.zshrc
        marker: "### {mark} Ansible managed: prompt"
        block: |
          # remove name from prompt
          prompt_context() {}
          BULLETTRAIN_PROMPT_ORDER=(
            uptime
            status
            custom
            context
            dir
            fnm
            git
            cmd_exec_time
          )
          
          # fnm: Node version manager
          prompt_fnm() {
            local fnm_prompt
            if type fnm >/dev/null 2>&1; then
              fnm_prompt=$(fnm current 2>/dev/null)
              [[ "${fnm_prompt}x" == "x" || "${fnm_prompt}" == "system" ]] && return
            elif type node >/dev/null 2>&1; then
              fnm_prompt="$(node --version)"
            else
              return
            fi
            fnm_prompt=${fnm_prompt}
            prompt_segment $BULLETTRAIN_NVM_BG $BULLETTRAIN_NVM_FG $BULLETTRAIN_NVM_PREFIX$fnm_prompt
          }

          # computer uptime
          prompt_uptime(){
              on=${${${(s: :)"$(uptime)"}[3]}%,}
              prompt_segment $BULLETTRAIN_TIME_BG $BULLETTRAIN_TIME_FG "[$on]"
          }

    - name: Ensure custom aliases
      blockinfile:
        dest: ~/.zshrc
        marker: "### {mark} Ansible managed: aliases"
        block: |
          alias zshconfig='vim ~/.zshrc'
          alias ohmyzsh='vim ~/.oh-my-zsh'
          alias home='deactivate; cd ~; clear'
          alias sgid-index='>&2 echo "starting sgid index update" &&
          cd ~/dev/gis.utah.gov &&
          source .env/bin/activate &&
          >&2 echo "switching to master branch" &&
          git checkout master &&
          >&2 echo "updating from remote" &&
          git up &&
          >&2 echo "running python" &&
          cd /scripts
          python datatable.py
          if git commit -am ":package: update sgid-index"
          then git push
          fi
          >&2 echo "done" && deactivate && cd ~/'
          if git commit -am ":package: update sgid-index"
          then git push
          fi
          >&2 echo "done" && deactivate && cd ~/'
          alias clip='pbcopy'
          alias grep='grep --colour=auto'
          alias ls='ls -GFh'

    - name: Ensure extra configuration
      file:
        path: ~/.zshenv
        state: file
        mode: 0700

    - name: Ensure extra configuration is used
      blockinfile:
        dest: ~/.zshrc
        marker: "### {mark} Ansible managed: env"
        block: |
          source ~/.zshenv
