- name: Python
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure Python 3 on path
      blockinfile:
        path: ~/.zshrc
        marker: "### {mark} Ansible managed: python3"
        block: |
          alias python='python3'
          export PATH=$HOME/Library/Python/3.7/bin:$PATH
    - name: Ensure pyodbc
      homebrew: 
        name: unixodbc
